run:
  timeout: 1m
  issues-exit-code: 2
  allow-parallel-runners: true
presets:
  - bugs
  - comment
  - complexity
  - error
  - format
  - import
  - metalinter
  - module
  - performance
  - sql
  - style
  - test
  - unused